apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
  labels:
    name: helloworld

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go
  namespace: helloworld
spec:
  template:
    spec:
      containers:
        - image: docker.io/timam/helloworld-go
          env:
            - name: TARGET
              value: "Go fron Frankfurt"