---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: helloworld.timam.io
spec:
  namespace: timam
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: timam
spec:
  template:
    spec:
      containers:
        - image: docker.io/timam/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v3"
  traffic:
    - revisionName: helloworld-00002
      percent: 0
      tag: v2
    - revisionName: helloworld-00003
      percent: 100
      tag: v3
---
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: helloworld.timam.io
  namespace: timam
spec:
  ref:
    name: helloworld
    kind: Service
    apiVersion: serving.knative.dev/v1
