apiVersion: v1
kind: Namespace
metadata:
  name: timam
  labels:
    name: timam

---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: helloworld.timam.io
spec:
  namespace: timam
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: timam
spec:
  template:
    spec:
      containers:
        - image: docker.io/timam/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v1"
---
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: helloworld.timam.io
  namespace: timam
spec:
  ref:
    name: helloworld
    kind: Service
    apiVersion: serving.knative.dev/v1
