apiVersion: v1
kind: Namespace
metadata:
  name: "timam"
  labels:
    name: "timam"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/timam/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v1"